server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: technical-service
          uri: lb://technical-service
          predicates:
            - Path=/api/engineers/**
            - Path=/api/administrators/**
            - Path=/api//managers/**
            - Path=/api/plans/**
        - id: hospital-service
          uri: lb://hospital-service
          predicates:
            - Path=/brands/**
            - Path=/medical_equipments/**
            - Path=/models/**
        - id: documentation-service
          uri: lb://documentation-service
          predicates:
            - Path=/engineerreport/**
            - Path=/finalreport/**
            - Path=/managerrequests/**
            - Path=/schedule/**
        - id: managementh-service
          uri: lb://managementh-service
            predicates:
              - Path=/hospitals/**

